apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example2
  namespace: default
  labels:
    app: nginx-example2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-example2
  template:
    metadata:
      labels:
        app: nginx-example2
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 100Mi
