apiVersion: v1
kind: Service
metadata:
  name: echo-headless
  labels:
    app: echo-headless
spec:
  clusterIP: None
  selector:
    app: echo-headless
  ports:
    - port: 80
      name: web
      targetPort: 80
      protocol: TCP
