apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-normal
  namespace: default
  labels:
    app: echo-normal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-normal
  template:
    metadata:
      labels:
        app: echo-normal
    spec:
      containers:
        - name: main
          image: ealen/echo-server
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 100Mi
