apiVersion: v1
kind: Service
metadata:
  name: nginx-example2
  namespace: default
spec:
  selector:
    app: nginx-example2
  type: ClusterIP
  ports:
    - name: nginx-example2
      protocol: TCP
      port: 80
      targetPort: 80
