apiVersion: v1
kind: Service
metadata:
  name: echo-normal
  namespace: default
spec:
  selector:
    app: echo-normal
  type: ClusterIP
  ports:
    - name: echo-normal
      protocol: TCP
      port: 80
      targetPort: 80
